"""agregar id_curso a tabla clase

Revision ID: 37b59e1b949c
Revises: 
Create Date: 2026-08-06 15:48:43.397769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37b59e1b949c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cuil'])

    with op.batch_alter_table('asistencia', schema=None) as batch_op:
        batch_op.drop_column('estado_asistencia')
        batch_op.drop_column('observaciones')

    with op.batch_alter_table('clase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_curso', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'curso', ['id_curso'], ['id_curso'])

    with op.batch_alter_table('clase_matricula', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_clm_matricula'), type_='foreignkey')

    with op.batch_alter_table('matricula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_curso', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'curso', ['id_curso'], ['id_curso'])

    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.alter_column('direccion',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_index(batch_op.f('email'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('direccion',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('matricula', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_curso')

    with op.batch_alter_table('clase_matricula', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_clm_matricula'), 'matricula', ['id_matricula'], ['id_matricula'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('clase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_curso')

    with op.batch_alter_table('asistencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('estado_asistencia', mysql.VARCHAR(length=20), nullable=False))

    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
